REGISTRY = {
    "strlen": [
        ("3char", "Three characters."),
        ("empty", "Empty string."),
        ("middleNUL", "String with a NUL-terminator in the middle."),
    ],
    "isalpha": [
        ("alpha_lower", "Lowercase alphabet (abc)."),
        ("alpha_upper", "Uppercase alphabet (ABC)."),
        ("digits", "Digits (0123456789)."),
        ("punctuation", "Punctuation marks (.,!?)."),
        ("nonprintable", "Characters below 32 in the ASCII table."),
        ("ext_ascii", "Characters above 127 in the ASCII table."),
    ],
    "atoi": [
        ("0", "Zero."),
        ("-100", "Negative number."),
        ("100", "Positive number."),
        ("++10", "Multiple leading plus signs."),
        ("-+1987", "Mixed leading signs."),
        ("+ 19", "Plus followed by space before digits."),
        ("-1", "Negative single digit."),
        ("1", "Positive single digit."),
        ("1+", "Trailing plus sign after number."),
        ('69   ', "Number with trailing spaces."),
        ("empty", "Empty string."),
        ("helloworld", "No digits in string."),
        ("helloworld10", "Digits after letters."),
        ("joinpunct", "Digits mixed with punctuation."),
        ("joinsign", "Digits mixed with sign characters."),
        ("joinspace", "Digits separated by spaces."),
        ("whitespace", "Leading whitespace before number."),
        ("zeroes", "Number with leading zeroes."),
        ("intmax", "Integer maximum."),
        ("intmin", "Integer minimum."),
    ],
}
